# Inclass Assignment-3 – COSC 2316 – Professor McCurry

#  Implemented by - Ryan Aparicio


import matplotlib.pyplot as plt
import math

def revenue(tax):
    #this is the equation that returns the revenue generated by the tax rate
    return (100 * (math.log(tax+1) - (tax-0.2)**2 + 0.4))
x = 10

def TaxPlot(tax):
    #this plots the revenue function
    xs = [x/1000 for x in range(1001)]
    ys = [revenue(x) for x in xs]
    plt.plot(xs,ys)
    plt.title('Tax Rates and Revenue')
    plt.xlabel('Tax Rate')
    plt.ylabel('Revenue')
    plt.plot(tax, revenue(tax), 'ro')
    plt.show()
    
def revenue_derivative(tax):
    #this is the derivative of the revenue function
    return 100*(1/(tax+1) - 2*(tax-0.2))

def max_revenue(step_size, threshold, maximum_iterations, iterations, current_rate):
    #this function maximizes the revenue function
    keep_going = True
    #this is the flag
    while(keep_going):
        rate_change = step_size * revenue_derivative(current_rate)
        current_rate = current_rate + rate_change
        #this is the new rate
        if(abs(rate_change) < threshold):
            keep_going = False
        #this is the threshold
        if(iterations > maximum_iterations):
            keep_going = False
        iterations = iterations + 1
    return current_rate

def main():
    current_rate = 0.7
    #current_rate = 0.699
    
    TaxPlot(current_rate)
    
    #print("the current revenuw is ", revenue(current_rate))
    print("CURRENT REVENUE DERIVATION BEFORE MAXING", revenue_derivative(current_rate))


    #setting the step size, threshold, and maximum iterations
    step_size = 0.001
    threshold = 0.0001
    maximum_iterations = 10000
    iterations = 0
    
    
    #calling the max_revenue function
    max_rate = max_revenue(step_size, threshold, maximum_iterations, iterations, current_rate)
    
    #plotting the revenue funciton after maximizing
    TaxPlot(max_rate)
    
    #outputting the results
    print("revenue derivative after maximizing: ", revenue_derivative(max_rate))
    print("maximized tax rate: ", max_rate)
    print ("maximized revenue: ", revenue(max_rate))
    
if __name__ == "__main__":
    main()